=== MakoTime/DMTools/schemas/entities/Creature.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "entities/Creature.schema.json",
    "title": "D&D 5e Creature",
    "description": "A creature in play, including player characters, NPCs, and monsters. Left open so Character and Monster may add fields.",
    "$comment": "version 0.5.0",
    "type": "object",
    "required": [
        "name"
    ],
    "properties": {
        "name": {
            "type": "string",
            "minLength": 1
        },
        "size": {
            "$ref": "../values/size.schema.json"
        },
        "creature_type": {
            "$ref": "../values/creature_type.schema.json"
        },
        "alignment": {
            "$ref": "../values/alignment.schema.json"
        },
        "ability_scores": {
            "$ref": "../components/ability_scores.schema.json"
        },
        "hit_points": {
            "$ref": "../components/hit_points.schema.json"
        },
        "hit_dice": {
            "$ref": "../components/hit_dice.schema.json"
        },
        "armor_class": {
            "type": "object",
            "required": [
                "value"
            ],
            "properties": {
                "value": {
                    "type": "integer",
                    "minimum": 0
                },
                "description": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "movement": {
            "type": "array",
            "items": {
                "$ref": "../components/movement.schema.json"
            }
        },
        "saving_throws": {
            "$ref": "../components/saving_throws.schema.json"
        },
        "skills": {
            "type": "object",
            "additionalProperties": {
                "type": "integer"
            }
        },
        "senses": {
            "type": "array",
            "items": {
                "$ref": "../components/sense.schema.json"
            }
        },
        "passive_perception": {
            "type": "integer",
            "minimum": 0
        },
        "languages": {
            "type": "array",
            "items": {
                "$ref": "../values/language.schema.json"
            },
            "uniqueItems": true
        },
        "proficiency_bonus": {
            "type": "integer",
            "minimum": 0
        },
        "condition_immunities": {
            "type": "array",
            "items": {
                "$ref": "../values/condition.schema.json"
            },
            "uniqueItems": true
        },
        "damage_immunities": {
            "type": "array",
            "items": {
                "$ref": "../values/damage_type.schema.json"
            },
            "uniqueItems": true
        },
        "damage_resistances": {
            "type": "array",
            "items": {
                "$ref": "../values/damage_type.schema.json"
            },
            "uniqueItems": true
        },
        "damage_vulnerabilities": {
            "type": "array",
            "items": {
                "$ref": "../values/damage_type.schema.json"
            },
            "uniqueItems": true
        },
        "features": {
            "type": "array",
            "items": {
                "$ref": "../components/feature.schema.json"
            }
        },
        "actions": {
            "type": "array",
            "items": {
                "$ref": "../components/action.schema.json"
            }
        },
        "reactions": {
            "type": "array",
            "items": {
                "$ref": "../components/action.schema.json"
            }
        },
        "legendary_actions": {
            "type": "array",
            "items": {
                "$ref": "../components/action.schema.json"
            }
        },
        "spell_casting": {
            "$ref": "../components/spell_casting.schema.json"
        },
        "roll_table": {
            "$ref": "../components/roll_table.schema.json"
        },
        "challenge_rating": {
            "type": [
                "number",
                "string"
            ]
        },
        "environments": {
            "type": "array",
            "items": {
                "type": "string",
                "minLength": 1
            },
            "uniqueItems": true
        },
        "description": {
            "type": "string",
            "input": "textarea"
        },
        "image": {
            "$ref": "../components/image.schema.json"
        },
        "source": {
            "$ref": "../values/source.schema.json"
        }
    },
    "additionalProperties": false
}

=== MakoTime/DMTools/tests/data/schemas/entities/creatures/beholder.json
{
    "name": "Beholder",
    "size": "large",
    "creature_type": "aberration",
    "alignment": {
        "order": "lawful",
        "morality": "evil"
    },
    "ability_scores": {
        "strength": 10,
        "dexterity": 14,
        "constitution": 18,
        "intelligence": 17,
        "wisdom": 15,
        "charisma": 17
    },
    "hit_points": {
        "maximum": 189,
        "current": 189,
        "temporary": 0
    },
    "hit_dice": {
        "count": 19,
        "dice": 10
    },
    "armor_class": {
        "value": 18,
        "description": "Natural armor"
    },
    "movement": [
        {
            "movement_type": "walk",
            "speed": {
                "distance": 0,
                "unit": "feet"
            }
        },
        {
            "movement_type": "fly",
            "speed": {
                "distance": 20,
                "unit": "feet"
            },
            "hover": true
        }
    ],
    "saving_throws": {
        "intelligence": 8,
        "wisdom": 7,
        "charisma": 8
    },
    "skills": {
        "perception": 12
    },
    "condition_immunities": [
        "prone"
    ],
    "senses": [
        {
            "type": "darkvision",
            "distance": 120,
            "distance_type": "feet"
        }
    ],
    "passive_perception": 22,
    "languages": [
        "Deep Speech",
        "Undercommon"
    ],
    "challenge_rating": 13,
    "features": [
        {
            "name": "Antimagic Cone",
            "description": "The beholder's central eye creates an area of antimagic, as in the antimagic field spell, in a 150-foot cone. At the start of each of its turns, the beholder decides which way the cone faces and whether the cone is active. The area works against the beholder's own eye rays."
        }
    ],
    "actions": [
        {
            "name": "Bite",
            "description": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 14 (4d6) piercing damage.",
            "target": {
                "targeting": "range",
                "range": {
                    "amount": 5,
                    "unit": "feet"
                },
                "count": {
                    "maximum": 1
                }
            },
            "effects": [
                {
                    "attack_hit": {
                        "type": "melee",
                        "bonus": 5,
                        "effects": [
                            {
                                "damage": {
                                    "type": "piercing",
                                    "roll": {
                                        "count": 4,
                                        "dice": 6
                                    }
                                }
                            }
                        ]
                    }
                }
            ]
        },
        {
            "name": "Eye Rays",
            "description": "The beholder shoots three of the following magical eye rays at random (reroll duplicates), choosing one to three targets it can see within 120 ft. of it.",
            "target": {
                "targeting": "range",
                "range": {
                    "amount": 120,
                    "unit": "feet"
                },
                "count": {
                    "minimum": 1,
                    "maximum": 3
                }
            }
        }
    ],
    "legendary_actions": [
        {
            "name": "Legendary Actions (3/Turn)",
            "description": "The beholder can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time, and only at the end of another creature's turn. The beholder regains spent legendary actions at the start of its turn."
        },
        {
            "name": "Eye Ray",
            "description": "The beholder uses one random eye ray."
        }
    ],
    "roll_table": {
        "dice": 10,
        "entries": [
            {
                "roll": 1,
                "result": "Charm Ray",
                "effects": [
                    {
                        "description": "The targeted creature must succeed on a DC 16 Wisdom saving throw or be charmed by the beholder for 1 hour, or until the beholder harms the creature."
                    }
                ]
            },
            {
                "roll": 2,
                "result": "Paralyzing Ray",
                "effects": [
                    {
                        "description": "The targeted creature must succeed on a DC 16 Constitution saving throw or be paralyzed for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success."
                    }
                ]
            },
            {
                "roll": 3,
                "result": "Fear Ray",
                "effects": [
                    {
                        "description": "The targeted creature must succeed on a DC 16 Wisdom saving throw or be frightened for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success."
                    }
                ]
            },
            {
                "roll": 4,
                "result": "Slowing Ray",
                "effects": [
                    {
                        "description": "The targeted creature must succeed on a DC 16 Dexterity saving throw. On a failed save, the target's speed is halved for 1 minute, it cannot take reactions, and it can take either an action or a bonus action on its turn, not both."
                    }
                ]
            },
            {
                "roll": 5,
                "result": "Enervation Ray",
                "effects": [
                    {
                        "description": "The targeted creature must make a DC 16 Constitution saving throw, taking half as much damage on a successful save."
                    },
                    {
                        "damage": {
                            "type": "necrotic",
                            "roll": {
                                "count": 8,
                                "dice": 8
                            }
                        }
                    }
                ]
            },
            {
                "roll": 6,
                "result": "Telekinetic Ray",
                "effects": [
                    {
                        "description": "If the target is a creature, it must succeed on a DC 16 Strength saving throw or be moved up to 30 ft. in any direction and restrained until the start of the beholder's next turn or until the beholder is incapacitated. If the target is an object weighing 300 pounds or less that isn't being worn or carried, it is moved up to 30 ft. in any direction."
                    }
                ]
            },
            {
                "roll": 7,
                "result": "Sleep Ray",
                "effects": [
                    {
                        "description": "The targeted creature must succeed on a DC 16 Wisdom saving throw or fall unconscious for 1 minute. The target awakens if it takes damage or another creature takes an action to wake it. This ray has no effect on constructs and undead."
                    }
                ]
            },
            {
                "roll": 8,
                "result": "Petrification Ray",
                "effects": [
                    {
                        "description": "The targeted creature must make a DC 16 Dexterity saving throw. On a failed save, the creature begins to turn to stone and is restrained. It must repeat the saving throw at the end of its next turn. On a success, the effect ends. On a failure, the creature is petrified."
                    }
                ]
            },
            {
                "roll": 9,
                "result": "Disintegration Ray",
                "effects": [
                    {
                        "damage": {
                            "type": "force",
                            "roll": {
                                "count": 10,
                                "dice": 8
                            }
                        }
                    },
                    {
                        "description": "If this damage reduces a creature to 0 hit points, its body becomes a pile of fine gray dust."
                    }
                ]
            },
            {
                "roll": 10,
                "result": "Death Ray",
                "effects": [
                    {
                        "damage": {
                            "type": "necrotic",
                            "roll": {
                                "count": 10,
                                "dice": 10
                            }
                        }
                    },
                    {
                        "description": "The target dices if the ray reduces it to 0 hit points."
                    }
                ]
            }
        ]
    },
    "environments": [
        "underdark"
    ],
    "source": {
        "text": "Monster Manual p. 28"
    }
}

=== MakoTime/DMTools/tests/data/schemas/entities/creatures/acolyte.json
{
    "name": "Acolyte",
    "size": "medium",
    "creature_type": "humanoid",
    "alignment": "any",
    "ability_scores": {
        "strength": 10,
        "dexterity": 10,
        "constitution": 10,
        "intelligence": 10,
        "wisdom": 14,
        "charisma": 11
    },
    "hit_points": {
        "maximum": 9,
        "current": 9,
        "temporary": 0
    },
    "hit_dice": {
        "count": 2,
        "dice": 8
    },
    "armor_class": {
        "value": 10
    },
    "movement": [
        {
            "movement_type": "walk",
            "speed": {
                "distance": 30,
                "unit": "feet"
            }
        }
    ],
    "skills": {
        "medicine": 4,
        "religion": 2
    },
    "passive_perception": 12,
    "languages": [
        "any one language (usually Common)"
    ],
    "challenge_rating": "1/4",
    "features": [
        {
            "name": "Spellcasting",
            "description": "The acolyte is a 1st-level spellcaster. Its spellcasting ability is Wisdom (spell save DC 12, +4 to hit with spell attacks). The acolyte has the following cleric spells prepared:"
        }
    ],
    "actions": [
        {
            "name": "Club",
            "description": "Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 2 (1d4) bludgeoning damage.",
            "type": "action",
            "target": {
                "targeting": "range",
                "range": {
                    "amount": 5,
                    "unit": "feet"
                }
            },
            "effects": [
                {
                    "attack_hit": {
                        "type": "melee_weapon",
                        "bonus": 2,
                        "effects": [
                            {
                                "damage": {
                                    "type": "bludgeoning",
                                    "roll": {
                                        "count": 1,
                                        "dice": 4
                                    },
                                    "modifier": 0
                                }
                            }
                        ]
                    }
                }
            ]
        }
    ],
    "spell_casting": {
        "ability": "wisdom",
        "save_dc": 12,
        "attack_bonus": 4,
        "spells_known": {
            "cantrips": [
                "light",
                "sacred flame",
                "thaumaturgy"
            ],
            "level_1": {
                "slots": 3,
                "spells": [
                    "bless",
                    "cure wounds",
                    "sanctuary"
                ]
            }
        }
    },
    "environments": [
        "urban"
    ],
    "source": {
        "text": "Monster Manual p. 342"
    }
}

=== MakoTime/DMTools/tests/data/schemas/entities/creatures/adult_blue_dracolich.json
{
    "name": "Adult Blue Dracolich",
    "size": "huge",
    "creature_type": "undead",
    "alignment": {
        "order": "lawful",
        "morality": "evil"
    },
    "ability_scores": {
        "strength": 25,
        "dexterity": 10,
        "constitution": 23,
        "intelligence": 16,
        "wisdom": 15,
        "charisma": 19
    },
    "hit_points": {
        "maximum": 225,
        "current": 225,
        "temporary": 0
    },
    "hit_dice": {
        "count": 18,
        "die": 12
    },
    "armor_class": {
        "value": 19,
        "description": "Natural armor"
    },
    "movement": [
        {
            "movement_type": "walk",
            "speed": {
                "distance": 40,
                "unit": "feet"
            }
        },
        {
            "movement_type": "burrow",
            "speed": {
                "distance": 30,
                "unit": "feet"
            }
        },
        {
            "movement_type": "fly",
            "speed": {
                "distance": 80,
                "unit": "feet"
            }
        }
    ],
    "saving_throws": {
        "dexterity": 5,
        "constitution": 11,
        "wisdom": 7,
        "charisma": 9
    },
    "skills": {
        "perception": 12,
        "stealth": 5
    },
    "senses": [
        {
            "type": "blindsight",
            "distance": 60,
            "distance_type": "feet"
        },
        {
            "type": "darkvision",
            "distance": 120,
            "distance_type": "feet"
        }
    ],
    "passive_perception": 22,
    "languages": [
        "Common",
        "Draconic"
    ],
    "condition_immunities": [
        "charmed",
        "exhaustion",
        "frightened",
        "paralyzed",
        "poisoned"
    ],
    "damage_immunities": [
        "lightning",
        "poison"
    ],
    "damage_resistances": [
        "necrotic"
    ],
    "damage_vulnerabilities": [],
    "features": [
        {
            "name": "Legendary Resistance (3/Day)",
            "description": "If the dracolich fails a saving throw, it can choose to succeed instead."
        },
        {
            "name": "Magic Resistance",
            "description": "The dracolich has advantage on saving throws against spells and other magical effects."
        }
    ],
    "actions": [
        {
            "name": "Multiattack",
            "description": "The dracolich can use its Frightful Presence. It then makes three attacks: one with its bite and two with its claws."
        },
        {
            "name": "Bite",
            "description": "Melee Weapon Attack: +12 to hit, reach 10 ft., one target. Hit: 18 (2d10+7) piercing damage plus 5 (1d10) lightning damage.",
            "effects": [
                {
                    "attack_hit": {
                        "type": "melee",
                        "bonus": 12,
                        "effects": [
                            {
                                "damage": {
                                    "type": "piercing",
                                    "roll": {
                                        "dice": 10,
                                        "count": 2
                                    },
                                    "modifier": 7
                                }
                            },
                            {
                                "damage": {
                                    "type": "lightning",
                                    "roll": {
                                        "dice": 10,
                                        "count": 1
                                    },
                                    "modifier": 0
                                }
                            }
                        ]
                    }
                }
            ]
        },
        {
            "name": "Claw",
            "description": "Melee Weapon Attack: +12 to hit, reach 5 ft., one target. Hit: 14 (2d6+7) slashing damage.",
            "effects": [
                {
                    "attack_hit": {
                        "type": "melee",
                        "bonus": 12,
                        "effects": [
                            {
                                "damage": {
                                    "type": "slashing",
                                    "roll": {
                                        "dice": 6,
                                        "count": 2
                                    },
                                    "modifier": 7
                                }
                            }
                        ]
                    }
                }
            ]
        },
        {
            "name": "Tail",
            "description": "Melee Weapon Attack: +12 to hit, reach 15 ft., one target. Hit: 16 (2d8+7) bludgeoning damage.",
            "effects": [
                {
                    "attack_hit": {
                        "type": "melee",
                        "bonus": 12,
                        "effects": [
                            {
                                "damage": {
                                    "type": "bludgeoning",
                                    "roll": {
                                        "dice": 8,
                                        "count": 2
                                    },
                                    "modifier": 7
                                }
                            }
                        ]
                    }
                }
            ]
        },
        {
            "name": "Frightful Presence",
            "description": "Each creature of the dracolich's choice that is within 120 feet of the dracolich and aware of it must succeed on a DC 18 Wisdom saving throw or become frightened for 1 minute. A creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success. If a creature's saving throw is successful or the effect ends for it, the creature is immune to the dracolich's Frightful Presence for the next 24 hours.",
            "effects": [
                {
                    "attack_save": {
                        "ability": "wisdom",
                        "dc": 18,
                        "failure": [
                            {
                                "condition": "frightened"
                            }
                        ]
                    }
                }
            ]
        },
        {
            "name": "Lightning Breath (Recharge 5-6)",
            "description": "The dracolich exhales lightning in a 90-foot line that is 5 feet wide. Each creature in that line must make a DC 20 Dexterity saving throw, taking 66 (12d10) lightning damage on a failed save, or half as much damage on a successful one.",
            "effects": [
                {
                    "attack_save": {
                        "ability": "dexterity",
                        "dc": 20,
                        "success": [
                            {
                                "damage": {
                                    "type": "lightning",
                                    "roll": {
                                        "dice": 10,
                                        "count": 12
                                    }
                                }
                            }
                        ],
                        "failure": [
                            {
                                "damage": {
                                    "type": "lightning",
                                    "roll": {
                                        "dice": 10,
                                        "count": 12
                                    }
                                }
                            }
                        ]
                    }
                }
            ]
        }
    ],
    "legendary_actions": [
        {
            "name": "Legendary Actions (3/Turn)",
            "description": "The dracolich can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time, and only at the end of another creature's turn. The dracolich regains spent legendary actions at the start of its turn."
        },
        {
            "name": "Detect",
            "description": "The dracolich makes a Wisdom (Perception) check."
        },
        {
            "name": "Tail Attack",
            "description": "The dracolich makes a tail attack."
        },
        {
            "name": "Wing Attack (Costs 2 Actions)",
            "description": "The dracolich beats its tattered wings. Each creature within 10 ft. of the dracolich must succeed on a DC 21 Dexterity saving throw or take 14 (2d6+7) bludgeoning damage and be knocked prone. After beating its wings this way, the dracolich can fly up to half its flying speed."
        }
    ],
    "challenge_rating": 17,
    "environments": [
        "desert"
    ],
    "source": {
        "text": "Monster Manual p. 84"
    }
}
