=== MakoTime/DMTools/schemas/entities/Creature.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "entities/Creature.schema.json",
    "title": "D&D 5e Creature",
    "description": "A creature in play, including player characters, NPCs, and monsters. Left open so Character and Monster may add fields.",
    "$comment": "version 0.5.0",
    "type": "object",
    "required": [
        "name"
    ],
    "properties": {
        "name": {
            "type": "string",
            "minLength": 1
        },
        "size": {
            "$ref": "../values/size.schema.json"
        },
        "creature_type": {
            "$ref": "../values/creature_type.schema.json"
        },
        "alignment": {
            "$ref": "../values/alignment.schema.json"
        },
        "ability_scores": {
            "$ref": "../components/ability_scores.schema.json"
        },
        "hit_points": {
            "$ref": "../components/hit_points.schema.json"
        },
        "hit_dice": {
            "$ref": "../components/hit_dice.schema.json"
        },
        "armor_class": {
            "type": "object",
            "required": [
                "value"
            ],
            "properties": {
                "value": {
                    "type": "integer",
                    "minimum": 0
                },
                "description": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "movement": {
            "type": "array",
            "items": {
                "$ref": "../components/movement.schema.json"
            }
        },
        "saving_throws": {
            "$ref": "../components/saving_throws.schema.json"
        },
        "skills": {
            "type": "object",
            "additionalProperties": {
                "type": "integer"
            }
        },
        "senses": {
            "type": "array",
            "items": {
                "$ref": "../components/sense.schema.json"
            }
        },
        "passive_perception": {
            "type": "integer",
            "minimum": 0
        },
        "languages": {
            "type": "array",
            "items": {
                "$ref": "../values/language.schema.json"
            },
            "uniqueItems": true
        },
        "proficiency_bonus": {
            "type": "integer",
            "minimum": 0
        },
        "condition_immunities": {
            "type": "array",
            "items": {
                "$ref": "../values/condition.schema.json"
            },
            "uniqueItems": true
        },
        "damage_immunities": {
            "type": "array",
            "items": {
                "$ref": "../values/damage_type.schema.json"
            },
            "uniqueItems": true
        },
        "damage_resistances": {
            "type": "array",
            "items": {
                "$ref": "../values/damage_type.schema.json"
            },
            "uniqueItems": true
        },
        "damage_vulnerabilities": {
            "type": "array",
            "items": {
                "$ref": "../values/damage_type.schema.json"
            },
            "uniqueItems": true
        },
        "features": {
            "type": "array",
            "items": {
                "$ref": "../components/feature.schema.json"
            }
        },
        "actions": {
            "type": "array",
            "items": {
                "$ref": "../components/action.schema.json"
            }
        },
        "reactions": {
            "type": "array",
            "items": {
                "$ref": "../components/action.schema.json"
            }
        },
        "legendary_actions": {
            "type": "array",
            "items": {
                "$ref": "../components/action.schema.json"
            }
        },
        "spell_casting": {
            "$ref": "../components/spell_casting.schema.json"
        },
        "roll_table": {
            "$ref": "../components/roll_table.schema.json"
        },
        "challenge_rating": {
            "type": [
                "number",
                "string"
            ]
        },
        "environments": {
            "type": "array",
            "items": {
                "type": "string",
                "minLength": 1
            },
            "uniqueItems": true
        },
        "description": {
            "type": "string",
            "input": "textarea"
        },
        "image": {
            "$ref": "../components/image.schema.json"
        },
        "source": {
            "$ref": "../values/source.schema.json"
        }
    },
    "additionalProperties": false
}

=== MakoTime/DMTools/tests/data/xml_files/monsters/adapted_results/elder_brain.json
{
    "name": "Elder Brain",
    "size": "large",
    "creature_type": "aberration",
    "alignment": {
        "order": "lawful",
        "morality": "evil"
    },
    "ability_scores": {
        "strength": 15,
        "dexterity": 10,
        "constitution": 20,
        "intelligence": 21,
        "wisdom": 19,
        "charisma": 24
    },
    "armor_class": {
        "value": 10
    },
    "hit_points": {
        "maximum": 210,
        "current": 210
    },
    "hit_dice": {
        "count": 20,
        "dice": 10
    },
    "movement": [
        {
            "movement_type": "walk",
            "speed": {
                "distance": 5,
                "unit": "feet"
            }
        },
        {
            "movement_type": "swim",
            "speed": {
                "distance": 10,
                "unit": "feet"
            }
        }
    ],
    "saving_throws": {
        "intelligence": 10,
        "wisdom": 9,
        "charisma": 12
    },
    "skills": {
        "arcana": 10,
        "deception": 12,
        "insight": 14,
        "intimidation": 12,
        "persuasion": 12
    },
    "senses": [
        {
            "type": "blindsight",
            "distance": 120,
            "distance_type": "feet"
        }
    ],
    "passive_perception": 14,
    "languages": [
        "understands Common",
        "Deep Speech",
        "and Undercommon but can't speak",
        "telepathy 5 miles"
    ],
    "features": [
        {
            "name": "Creature Sense",
            "description": "The elder brain is aware of the presence of creatures within 5 miles of it that have an Intelligence score of 4 or higher. It knows the distance and direction to each creature. as well as each one's intelligence score, but can’t sense anything else about it. A creature protected by a mind blank spell. a nondetection spell, or similar magic can’t be perceived in this manner."
        },
        {
            "name": "Innate Spellcasting (Psionics)",
            "description": "The elder brain’s innate spellcasting ability is Intelligence (spell save DC 18). It can innately cast the following spells, requiring no components:\n\nAt will: detect thoughts, levitate\n\n1/day each: dominate monster, plane shift (self only)"
        },
        {
            "name": "Legendary Resistance (3/Day)",
            "description": "If the elder brain fails a saving throw, it can choose to succeed instead."
        },
        {
            "name": "Magic Resistance",
            "description": "The elder brain has advantage on saving throws against spells and other magical effects."
        },
        {
            "name": "Telepathic Hub",
            "description": "The elder brain can use its telepathy to initiate and maintain telepathic conversations with up to ten creatures at a time. The elder brain can let those creatures telepathically hear each other while connected in this way."
        }
    ],
    "actions": [
        {
            "name": "Tentacle",
            "description": "Melee Weapon Attack: +7 to hit, reach 30 ft., one target. Hit: 20 (4d8+2) bludgeoning damage. If the target is a Huge or smaller creature, it is grappled (escape DC 15) and takes 9 (1d8+5) psychic damage at the start of each of its turns until the grapple ends. The elder brain can have up to four targets grappled at a time.\n\nGrappled:\n• A grappled creature's speed becomes 0, and it can't benefit from any bonus to its speed.\n\n• The condition ends if the grappler is incapacitated.\n\n• The condition also ends if an effect removes the grappled creature from the reach of the grappler or grappling effect, such as when a creature is hurled away by the thunderwave spell."
        },
        {
            "name": "Mind Blast (Recharge 5-6)",
            "description": "The elder brain magically emits psychic energy. Creatures of the elder brain's choice within 60 feet of it must succeed on a DC 18 Intelligence saving throw or take 32 (5d10+5) psychic damage and be stunned for 1 minute. A target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.\n\nStunned:\n• A stunned creature is incapacitated, meaning it can't take actions or reactions, can't move, and can speak only falteringly.\n\n• The creature automatically fails Strength and Dexterity saving throws.\n\n• Attack rolls against the creature have advantage."
        },
        {
            "name": "Psychic Link",
            "description": "The elder brain targets one incapacitated creature it can perceive with its Creature Sense trait and establishes a psychic link with that creature. Until the psychic link ends, the elder brain can perceive everything the target senses. The target becomes aware that something is linked to its mind once it is no longer incapacitated, and the elder brain can terminate the link at any time (no action required). The target can use an action on its turn to attempt to break the psychic link, doing so with a successful DC 18 Charisma saving throw. On a successful save, the target takes 10 (3d6) psychic damage. The psychic link also ends if the target and the elder brain are more than 5 miles apart, with no consequences to the target. The elder brain can form psychic links with up to ten creatures at a time."
        },
        {
            "name": "Sense Thoughts",
            "description": "The elder brain targets a creature with which it has a psychic link. The elder brain gains insight into the target’s reasoning, its emotional state, and thoughts that loom large in its mind (including things the target worries about, loves, or hates). The elder brain can also make a Charisma (Deception) check with advantage to deceive the target's mind into thinking it believes one idea or feels a particular emotion. The target contests this attempt with a Wisdom (Insight) check. If the elder brain succeeds, the mind believes the deception for 1 hour or until evidence of the lie is presented to the target."
        }
    ],
    "legendary_actions": [
        {
            "name": "Legendary Actions (3/Turn)",
            "description": "The elder brain can take 3 legendary actions, choosing from the options below. It can take only one legendary action at a time and only at the end of another creature’s turn. The elder brain regains spent legendary actions at the start of its turn."
        },
        {
            "name": "Tentacle",
            "description": "The elder brain makes a tentacle attack."
        },
        {
            "name": "Break Concentration",
            "description": "The elder brain targets a creature within 120 feet of it with which it has a psychic link. The elder brain breaks the creature’s concentration on a spell it has cast. The creature also takes 1d4 psychic damage per level of the spell."
        },
        {
            "name": "Psychic Pulse",
            "description": "The elder brain targets a creature within 120 feet of it with which it has a psychic link. Enemies of the elder brain within 10 feet of that creature take 10 (3d6) psychic damage."
        },
        {
            "name": "Sever Psychic Link",
            "description": "The elder brain targets a creature within 120 feet of it with which it has a psychic link. The elder brain ends the link, causing the creature to have disadvantage on all ability checks, attack rolls, and saving throws until the end of the creature’s next turn."
        }
    ],
    "challenge_rating": 14.0,
    "environments": [
        "underdark"
    ]
}

=== MakoTime/DMTools/tests/data/xml_files/monsters/adapted_results/beholder.json
{
    "name": "Beholder",
    "size": "large",
    "creature_type": "aberration",
    "alignment": {
        "order": "lawful",
        "morality": "evil"
    },
    "ability_scores": {
        "strength": 10,
        "dexterity": 14,
        "constitution": 18,
        "intelligence": 17,
        "wisdom": 15,
        "charisma": 17
    },
    "armor_class": {
        "value": 18,
        "description": "natural armor"
    },
    "hit_points": {
        "maximum": 189,
        "current": 189
    },
    "hit_dice": {
        "count": 19,
        "dice": 10
    },
    "movement": [
        {
            "movement_type": "walk",
            "speed": {
                "distance": 0,
                "unit": "feet"
            }
        },
        {
            "movement_type": "fly",
            "speed": {
                "distance": 20,
                "unit": "feet"
            },
            "hover": true
        }
    ],
    "saving_throws": {
        "intelligence": 8,
        "wisdom": 7,
        "charisma": 8
    },
    "skills": {
        "perception": 12
    },
    "condition_immunities": [
        "prone"
    ],
    "senses": [
        {
            "type": "darkvision",
            "distance": 120,
            "distance_type": "feet"
        }
    ],
    "passive_perception": 22,
    "languages": [
        "Deep Speech",
        "Undercommon"
    ],
    "features": [
        {
            "name": "Antimagic Cone",
            "description": "The beholder's central eye creates an area of antimagic, as in the antimagic field spell, in a 150-foot cone. At the start of each of its turns, the beholder decides which way the cone faces and whether the cone is active. The area works against the beholder's own eye rays."
        }
    ],
    "actions": [
        {
            "name": "Bite",
            "description": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 14 (4d6) piercing damage."
        },
        {
            "name": "Eye Rays",
            "description": "The beholder shoots three of the following magical eye rays at random (reroll duplicates), choosing one to three targets it can see within 120 ft. of it:\n1. Charm Ray. The targeted creature must succeed on a DC 16 Wisdom saving throw or be charmed by the beholder for 1 hour, or until the beholder harms the creature.\n2. Paralyzing Ray. The targeted creature must succeed on a DC 16 Constitution saving throw or be paralyzed for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.\n3. Fear Ray. The targeted creature must succeed on a DC 16 Wisdom saving throw or be frightened for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.\n4. Slowing Ray. The targeted creature must succeed on a DC 16 Dexterity saving throw. On a failed save, the target's speed is halved for 1 minute. In addition, the creature can't take reactions, and it can take either an action or a bonus action on its turn, not both. The creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.\n5. Enervation Ray. The targeted creature must make a DC 16 Constitution saving throw, taking 36 (8d8) necrotic damage on a failed save, or half as much damage on a successful one.\n6. Telekinetic Ray. If the target is a creature, it must succeed on a DC 16 Strength saving throw or the beholder moves it up to 30 ft. in any direction. It is restrained by the ray's telekinetic grip until the start of the beholder's next turn or until the beholder is incapacitated.\nIf the target is an object weighing 300 pounds or less that isn't being worn or carried, it is moved up to 30 ft. in any direction. The beholder can also exert fine control on objects with this ray, such as manipulating a simple tool or opening a door or a container.\n7. Sleep Ray. The targeted creature must succeed on a DC 16 Wisdom saving throw or fall asleep and remain unconscious for 1 minute. The target awakens if it takes damage or another creature takes an action to wake it. This ray has no effect on constructs and undead.\n8. Petrification Ray. The targeted creature must make a DC 16 Dexterity saving throw. On a failed save, the creature begins to turn to stone and is restrained. It must repeat the saving throw at the end of its next turn. On a success, the effect ends. On a failure, the creature is petrified until freed by the greater restoration spell or other magic.\n9. Disintegration Ray. If the target is a creature, it must succeed on a DC 16 Dexterity saving throw or take 45 (10d8) force damage. If this damage reduces the creature to 0 hit points, its body becomes a pile of fine gray dust.\nIf the target is a Large or smaller nonmagical object or creation of magical force, it is disintegrated without a saving throw. If the target is a Huge or larger object or creation of magical force, this ray disintegrates a 10-foot cube of it.\n10. Death Ray. The targeted creature must succeed on a DC 16 Dexterity saving throw or take 55 (10d10) necrotic damage. The target dies if the ray reduces it to 0 hit points.\n\nCharmed:\n• A charmed creature can't attack the charmer or target the charmer with harmful abilities or magical effects.\n\n• The charmer has advantage on any ability check to interact socially with the creature.\n\nFrightened:\n• A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight.\n\n• The creature can't willingly move closer to the source of its fear.\n\nParalyzed:\n• A paralyzed creature is incapacitated, meaning it can't take actions or reactions, and can't move or speak.\n\n• The creature automatically fails Strength and Dexterity saving throws.\n\n• Attack rolls against the creature have advantage.\n\n• Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature.\n\nPetrified:\n• A petrified creature is transformed, along with any nonmagical object it is wearing or carrying, into a solid inanimate substance (usually stone). Its weight increases by a factor of ten, and it ceases aging.\n\n• The creature is incapacitated (meaning it can't take actions or reactions), can't move or speak, and is unaware of its surroundings.\n\n• Attack rolls against the creature have advantage.\n\n• The creature automatically fails Strength and Dexterity saving throws.\n\n• The creature has resistance to all damage.\n\n• The creature is immune to poison and disease, although a poison or disease already in its system is suspended, not neutralized.\n\nRestrained:\n• A restrained creature's speed becomes 0, and it can't benefit from any bonus to its speed.\n\n• Attack rolls against the creature have advantage, and the creature's attack rolls have disadvantage.\n\n• The creature has disadvantage on Dexterity saving throws.\n\nUnconscious:\n• An unconscious creature is incapacitated, meaning it can't take actions or reactions, can't move or speak, and is unaware of its surroundings.\n\n• The creature drops whatever it's holding and falls prone.\n\n• The creature automatically fails Strength and Dexterity saving throws.\n\n• Attack rolls against the creature have advantage.\n\n• Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature."
        }
    ],
    "legendary_actions": [
        {
            "name": "Legendary Actions (3/Turn)",
            "description": "The beholder can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time, and only at the end of another creature's turn. The beholder regains spent legendary actions at the start of its turn."
        },
        {
            "name": "Eye Ray",
            "description": "The beholder uses one random eye ray."
        }
    ],
    "challenge_rating": 13.0,
    "environments": [
        "underdark"
    ]
}

=== MakoTime/DMTools/tests/data/xml_files/monsters/adapted_results/purple_worm.json
{
    "name": "Purple Worm",
    "size": "gargantuan",
    "creature_type": "monstrosity",
    "alignment": "unaligned",
    "ability_scores": {
        "strength": 28,
        "dexterity": 7,
        "constitution": 22,
        "intelligence": 1,
        "wisdom": 8,
        "charisma": 4
    },
    "armor_class": {
        "value": 18,
        "description": "natural armor"
    },
    "hit_points": {
        "maximum": 247,
        "current": 247
    },
    "hit_dice": {
        "count": 15,
        "dice": 20
    },
    "movement": [
        {
            "movement_type": "walk",
            "speed": {
                "distance": 50,
                "unit": "feet"
            }
        },
        {
            "movement_type": "burrow",
            "speed": {
                "distance": 30,
                "unit": "feet"
            }
        }
    ],
    "saving_throws": {
        "constitution": 11,
        "wisdom": 4
    },
    "senses": [
        {
            "type": "blindsight",
            "distance": 30,
            "distance_type": "feet"
        },
        {
            "type": "tremorsense",
            "distance": 60,
            "distance_type": "feet"
        }
    ],
    "passive_perception": 9,
    "features": [
        {
            "name": "Tunneler",
            "description": "The worm can burrow through solid rock at half its burrow speed and leaves a 10-foot-diameter tunnel in its wake."
        }
    ],
    "actions": [
        {
            "name": "Multiattack",
            "description": "The worm makes two attacks: one with its bite and one with its stinger."
        },
        {
            "name": "Bite",
            "description": "Melee Weapon Attack: +9 to hit, reach 10 ft., one target. Hit: 22 (3d8+9) piercing damage. If the target is a Large or smaller creature, it must succeed on a DC 19 Dexterity saving throw or be swallowed by the worm. A swallowed creature is blinded and restrained, it has total cover against attacks and other effects outside the worm, and it takes 21 (6d6) acid damage at the start of each of the worm's turns.\nIf the worm takes 30 damage or more on a single turn from a creature inside it, the worm must succeed on a DC 21 Constitution saving throw at the end of that turn or regurgitate all swallowed creatures, which fall prone in a space within 10 feet of the worm. If the worm dies, a swallowed creature is no longer restrained by it and can escape from the corpse by using 20 feet of movement, exiting prone.\n\nBlinded:\n• A blinded creature can't see and automatically fails any ability check that requires sight.\n\n• Attack rolls against the creature have advantage, and the creature's attack rolls have disadvantage.\n\nProne:\n• A prone creature's only movement option is to crawl, unless it stands up and thereby ends the condition.\n\n• The creature has disadvantage on attack rolls.\n\n• An attack roll against the creature has advantage if the attacker is within 5 feet of the creature. Otherwise, the attack roll has disadvantage.\n\nRestrained:\n• A restrained creature's speed becomes 0, and it can't benefit from any bonus to its speed.\n\n• Attack rolls against the creature have advantage, and the creature's attack rolls have disadvantage.\n\n• The creature has disadvantage on Dexterity saving throws."
        },
        {
            "name": "Tail Stinger",
            "description": "Melee Weapon Attack: +9 to hit, reach 10 ft., one creature. Hit: 19 (3d6+9) piercing damage, and the target must make a DC 19 Constitution saving throw, taking 42 (12d6) poison damage on a failed save, or half as much damage on a successful one."
        }
    ],
    "challenge_rating": 15.0,
    "environments": [
        "desert",
        "underdark"
    ]
}
