=== MakoTime/DMTools/schemas/entities/Spell.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "entities/Spell.schema.json",
    "title": "D&D 5e Spell",
    "description": "A spell in the catalog.",
    "$comment": "version 0.4.0",
    "type": "object",
    "required": [
        "name",
        "description",
        "level",
        "casting_time",
        "components",
        "duration"
    ],
    "properties": {
        "name": {
            "type": "string",
            "minLength": 1
        },
        "description": {
            "type": "string",
            "input": "textarea"
        },
        "higher_level": {
            "type": "string",
            "input": "textarea"
        },
        "level": {
            "$ref": "../values/spell_level.schema.json"
        },
        "school": {
            "$ref": "../values/spell_school.schema.json"
        },
        "classes": {
            "description": "Class lists that include this spell.",
            "type": "array",
            "items": {
                "$ref": "../values/class_name.schema.json"
            },
            "uniqueItems": true
        },
        "casting_time": {
            "$ref": "../components/casting_time.schema.json"
        },
        "target": {
            "$ref": "../components/target.schema.json"
        },
        "components": {
            "type": "array",
            "items": {
                "$ref": "../values/spell_component.schema.json"
            },
            "uniqueItems": true
        },
        "material": {
            "$ref": "../components/material_component.schema.json"
        },
        "ritual": {
            "type": "boolean",
            "default": false
        },
        "concentration": {
            "type": "boolean",
            "default": false
        },
        "duration": {
            "$ref": "../components/duration_amount.schema.json"
        },
        "effects": {
            "type": "array",
            "items": {
                "$ref": "../components/effect.schema.json"
            }
        },
        "roll_table": {
            "$ref": "../components/roll_table.schema.json"
        },
        "tags": {
            "type": "array",
            "items": {
                "$ref": "../values/tag.schema.json"
            },
            "uniqueItems": true
        },
        "source": {
            "$ref": "../values/source.schema.json"
        },
        "grants": {
            "type": "array",
            "items": {
                "$ref": "../components/grant.schema.json"
            }
        }
    },
    "additionalProperties": false
}

=== MakoTime/DMTools/tests/data/schemas/entities/spells/prismatic_spray.json
{
    "name": "Prismatic Spray",
    "description": "Eight multicolored rays of light flash from your hand. Each ray is a different color and has a different power and purpose. Each creature in a 60-foot cone must make a Dexterity saving throw. For each target, roll a d8 to determine which color ray affects it.",
    "level": 7,
    "casting_time": {
        "amount": 1,
        "unit": "action"
    },
    "target": {
        "targeting": "self",
        "zone": {
            "type": "cone",
            "size": 60
        }
    },
    "components": [
        "verbal",
        "somatic"
    ],
    "duration": {
        "duration": "instantaneous"
    },
    "school": "evocation",
    "classes": [
        "sorcerer",
        "wizard",
        "bard"
    ],
    "roll_table": {
        "dice": 8,
        "entries": [
            {
                "roll": 1,
                "result": "Red",
                "effects": [
                    {
                        "attack_save": {
                            "ability": "dexterity",
                            "failure": [
                                {
                                    "damage": {
                                        "type": "fire",
                                        "roll": {
                                            "dice": 6,
                                            "count": 10
                                        }
                                    }
                                }
                            ],
                            "success": [
                                {
                                    "damage": {
                                        "type": "fire",
                                        "roll": {
                                            "dice": 6,
                                            "count": 10
                                        }
                                    },
                                    "description": "(Halved)"
                                }
                            ]
                        }
                    }
                ]
            },
            {
                "roll": 2,
                "result": "Orange",
                "effects": [
                    {
                        "attack_save": {
                            "ability": "dexterity",
                            "failure": [
                                {
                                    "damage": {
                                        "type": "acid",
                                        "roll": {
                                            "dice": 6,
                                            "count": 10
                                        }
                                    }
                                }
                            ],
                            "success": [
                                {
                                    "damage": {
                                        "type": "acid",
                                        "roll": {
                                            "dice": 6,
                                            "count": 10
                                        }
                                    },
                                    "description": "(Halved)"
                                }
                            ]
                        }
                    }
                ]
            },
            {
                "roll": 3,
                "result": "Yellow",
                "effects": [
                    {
                        "attack_save": {
                            "ability": "dexterity",
                            "failure": [
                                {
                                    "damage": {
                                        "type": "lightning",
                                        "roll": {
                                            "dice": 6,
                                            "count": 10
                                        }
                                    }
                                }
                            ],
                            "success": [
                                {
                                    "damage": {
                                        "type": "lightning",
                                        "roll": {
                                            "dice": 6,
                                            "count": 10
                                        }
                                    },
                                    "description": "(Halved)"
                                }
                            ]
                        }
                    }
                ]
            },
            {
                "roll": 4,
                "result": "Green",
                "effects": [
                    {
                        "attack_save": {
                            "ability": "dexterity",
                            "failure": [
                                {
                                    "damage": {
                                        "type": "poison",
                                        "roll": {
                                            "dice": 6,
                                            "count": 10
                                        }
                                    }
                                }
                            ],
                            "success": [
                                {
                                    "damage": {
                                        "type": "poison",
                                        "roll": {
                                            "dice": 6,
                                            "count": 10
                                        }
                                    },
                                    "description": "(Halved)"
                                }
                            ]
                        }
                    }
                ]
            },
            {
                "roll": 5,
                "result": "Blue",
                "effects": [
                    {
                        "attack_save": {
                            "ability": "dexterity",
                            "failure": [
                                {
                                    "damage": {
                                        "type": "cold",
                                        "roll": {
                                            "dice": 6,
                                            "count": 10
                                        }
                                    }
                                }
                            ],
                            "success": [
                                {
                                    "damage": {
                                        "type": "cold",
                                        "roll": {
                                            "dice": 6,
                                            "count": 10
                                        }
                                    },
                                    "description": "(Halved)"
                                }
                            ]
                        }
                    }
                ]
            },
            {
                "roll": 6,
                "result": "Indigo",
                "effects": [
                    {
                        "attack_save": {
                            "ability": "dexterity",
                            "failure": [
                                {
                                    "condition": "restrained"
                                },
                                {
                                    "description": "The target must make a Constitution saving throw at the end of each of its turns. If it successfully saves three times, the spell ends. If it fails its save three times, it permanently turns to stone and is subjected to the petrified condition. The successes and failures don't need to be consecutive."
                                }
                            ]
                        }
                    }
                ]
            },
            {
                "roll": 7,
                "result": "Violet",
                "effects": [
                    {
                        "attack_save": {
                            "ability": "dexterity",
                            "failure": [
                                {
                                    "condition": "blinded"
                                },
                                {
                                    "description": "The target must make a Wisdom saving throw at the start of your next turn. A successful save ends the blindness. If it fails that save, the creature is transported to another plane of existence of the DM's choosing and is no longer blinded."
                                }
                            ]
                        }
                    }
                ]
            },
            {
                "roll": 8,
                "result": "Special",
                "effects": [
                    {
                        "description": "The target is struck by two rays. Roll twice more, rerolling any 8."
                    }
                ]
            }
        ]
    },
    "source": {
        "text": "Player's Handbook p. 267"
    }
}
